development:
  sessions:
    default:
      database: oompa_development
      hosts:
        - <%= ENV['MONGO_URL'] || 'localhost' %>:27017
test:
  sessions:
    default:
      database: oompa_test
      hosts:
        - <%= ENV['MONGO_URL'] || 'localhost' %>:27017
production:
  sessions:
    default:
      database: oompa_production
      hosts:
        - <%= ENV['MONGODB_PORT_27017_TCP_ADDR'] || 'localhost' %>:27017
