development:
  clients:
    default:
      database: oompa_development
      hosts:
        - <%= ENV['MONGO_URL'] || 'localhost' %>:27017
      options:
        server_selection_timeout: 1
test:
  clients:
    default:
      database: oompa_test
      hosts:
        - <%= ENV['MONGO_URL'] || 'localhost' %>:27017
      options:
        server_selection_timeout: 1
production:
  clients:
    default:
      database: oompa_production
      hosts:
        - <%= ENV['MONGODB_PORT_27017_TCP_ADDR'] || 'localhost' %>:27017
