development:
  clients:
    default:
      database: oompa_development
      hosts:
        - <%= ENV['MONGO_URL'] || '127.0.0.1' %>:27017
test:
  clients:
    default:
      database: oompa_test
      hosts:
        - <%= ENV['MONGO_URL'] || '127.0.0.1' %>:27017
production:
  clients:
    default:
      database: oompa_production
      hosts:
        - <%= ENV['MONGODB_PORT_27017_TCP_ADDR'] || '127.0.0.1' %>:27017
